export { default as westOfHouse } from './westOfHouse'
export { default as northOfHouse } from './northOfHouse'
export { default as southOfHouse } from './southOfHouse'
export { default as behindHouse } from './behindHouse'
export { default as kitchen } from './kitchen'
export { default as upTree } from './upTree'
export { default as clearing } from './clearing'
export { forestPath, forest1, forest2, forest3, forest4 } from './forest'
// export { default as forest2 } from './forest2'
// export { default as forest3 } from './forest3'
// export { default as forest4 } from './forest4'
