export {default as MOVE} from './MOVE'
export {default as LOOK} from './LOOK'
export {default as TAKE} from './TAKE'
export {default as DROP} from './DROP'
export {default as LIGHT} from './LIGHT'
export {default as OPEN} from './OPEN'
export {default as EXAMINE} from './EXAMINE'
export const READ = 'READ'
